# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4.1.0
      with:
        # Version of pnpm to install
        version: 10.6.1 # optional
        # Where to store pnpm files
        # dest: # optional, default is ~/setup-pnpm
        # If specified, run `pnpm install`
        # run_install: # optional, default is null
        # File path to the package.json to read "packageManager" configuration
        # package_json_file: # optional, default is package.json
        # When set to true, @pnpm/exe, which is a Node.js bundled package, will be installed, enabling using pnpm without Node.js.
        # standalone: # optional, default is false
    - name: Install dependencies
      working-directory: .
      run: pnpm install
    - name: Build project
      working-directory: .
      run: pnpm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # 假设打包后的文件在 dist 目录，根据实际情况修改  
