name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:  # 仅保留合法权限
      id-token: write  # 若无需 OIDC 令牌，可删除此行
      contents: read   # 读取代码的权限（必需）
      pages: write     # 部署到 Pages 的权限（官方动作必需）
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        version: 10.6.1
        run_install: true
        cache: true

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Build project
      working-directory: .
      run: pnpm run build

    - name: Upload deployment artifact  # 必需步骤：上传工件到 GitHub
      uses: actions/upload-artifact@v4
      with:
        name: github-pages  # 固定名称，与官方部署动作匹配
        path: ./dist        # 构建输出目录（与你的项目一致）

    - name: Deploy to GitHub Pages
      if: success()
      uses: actions/deploy-pages@v4.0.5  # 官方部署动作，自动关联同名工件
